### ISSUE TITLE
Issue on page /more_dynamics.html

### ISSUE THREAD

**Issue by riuriuriuriu** [UTokyo-ICEPP/qc-workbook#2]
According to [Martinez et al. ](https://arxiv.org/pdf/1605.04570.pdf), the first term of the Hamiltonian (9) on the page would be wrong.

**Comment by yiiyama** [comment]
If you are talking about the sign of the Phi_{j} e^{-theta_j} Phi_{j+1}^{dagger} term, it's positive because the Phi operators are fermionic (anticommuting). If not, please let me know what the problem is.

**Comment by riuriuriuriu** [comment]
I'm sorry, I misunderstood. I appreciate your explanation.
